# -*- coding: utf-8 -*-
"""Ordinary_Kriging_di_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EtD7HVti2xNGCZOovFvYtYz4zFDSyzB0

**Install Package**
"""

#pip install pyinterp
#! pip install pyKriging
#! pip install gstools
! pip install pykrige

"""**Import Libary**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pykrige.ok import OrdinaryKriging

"""**Import Data Training**"""

! gdown --id 13qbittcVHYQBcBUkTy60ZGB-hTn3od8m

datatraining = pd.read_excel('/content/Data Training.xlsx')
datatraining

# Extract the necessary columns
latitude = datatraining['Latitute'].values
longitude = datatraining['Longtitute'].values
value = datatraining['COD 2024'].values

"""**Import Data Testing**"""

! gdown --id 1A-evARjN-LwCSDsjpkP_Imyb2WVgxugA

datatesting = pd.read_excel('/content/Data Testing.xlsx')
datatesting

# Extract the necessary columns
gridy = datatesting['Latitute'].values
gridx= datatesting['Longtitute'].values

"""**Prediksi dengan Ordinary Kriging**"""

# Perform Ordinary Kriging using the spherical variogram model
OK = OrdinaryKriging(longitude,
                     latitude,
                     value,
                     variogram_model='spherical',
                     coordinates_type='geographic',
                     verbose=True,
                     enable_plotting=True)

# Hasil interpolasi Kriging untuk 10 data testing
z_interp, ss = OK.execute('points', gridx, gridy)
pd.DataFrame(z_interp)