# -*- coding: utf-8 -*-
"""WaterKrigingCODBOD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJbBRwREejqmofx-Hw_qy4q2EFb-2NYJ
"""

pip install pandas numpy pykrige scikit-learn

import numpy as np
import pandas as pd
from pykrige.ok import OrdinaryKriging
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

# Membaca dataset
data = pd.read_csv('/content/Data Training (3).csv')

# Menampilkan beberapa baris pertama untuk melihat struktur data
print(data.head())

# Menyimpan fitur dan target
X = data[['latitute', 'longitude']]  # Lokasi
y = data[['COD2023', 'COD2024', 'BOD2023', 'BOD2024']]  # Kualitas air

scaler = StandardScaler()
y_scaled = scaler.fit_transform(y)

def fit_kriging_model(X, y, parameter):
    OK = OrdinaryKriging(
        X['longitude'], X['latitute'], y[parameter],
        variogram_model='spherical', verbose=True, enable_plotting=False
    )
    return OK

# Membuat model Kriging untuk setiap parameter
kriging_models = {}
parameters = ['COD2023', 'COD2024', 'BOD2023', 'BOD2024']

for param in parameters:
    kriging_models[param] = fit_kriging_model(X, data, param)

print(data.dtypes)

def predict_quality(latitude, longitude):
    predicted_values = {}
    for param in parameters:
        z, ss = kriging_models[param].execute('points', [longitude], [latitude])
        predicted_values[param] = z[0]  # Ambil nilai prediksi

    # Mengembalikan nilai yang diprediksi
    return predicted_values

# Contoh penggunaan
latitude_input = -6.1751
longitude_input = 106.8650

predicted_quality = predict_quality(latitude_input, longitude_input)
print(predicted_quality)

def fit_kriging_model(X, y, parameter):
    OK = OrdinaryKriging(
        X['longitude'], X['latitute'], y[parameter],
        variogram_model='spherical', verbose=True, enable_plotting=False
    )
    return OK

# Membuat model Kriging untuk setiap parameter
kriging_models = {}
parameters = ['COD2023', 'COD2024', 'BOD2023', 'BOD2024']

for param in parameters:
    kriging_models[param] = fit_kriging_model(data[['latitute', 'longitude']], data, param)

def predict_quality(latitude, longitude):
    predicted_values = {}
    for param in parameters:
        # Eksekusi model Kriging
        z, ss = kriging_models[param].execute('points', [longitude], [latitude])
        predicted_values[param] = z[0]

    return predicted_values

# Contoh penggunaan
latitude_input = -6.1751
longitude_input = 106.8650

predicted_quality = predict_quality(latitude_input, longitude_input)
print(predicted_quality)

latitude_input = -7.942
longitude_input = 110.371

predicted_quality = predict_quality(latitude_input, longitude_input)
print(predicted_quality)